name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Mengambil kode dari repositori
    - uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # Instal dependensi dan flake8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instal semua dependensi yang ada di requirements.txt
        pip install flake8 pytest  # Instal flake8 dan pytest jika belum ada

    # Verifikasi instalasi flake8
    - name: Verify flake8 installation
      run: |
        pip show flake8  # Pastikan flake8 terinstal dengan benar
        pip show pytest  # Pastikan pytest terinstal dengan benar

    # Cek struktur direktori untuk memverifikasi ada atau tidaknya src/ dan tests/
    - name: Check directories structure
      run: |
        ls -R  # Menampilkan seluruh struktur direktori untuk memastikan src/ dan tests/ ada

    # Jalankan pengecekan kode dengan flake8
    - name: Lint with flake8
      run: |
        flake8 src/ tests/ --max-line-length=120 --exclude=src/static  # Lakukan pengecekan kode

    # Jalankan pengujian dengan pytest
    - name: Run tests
      env:
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        SOLSCAN_API_KEY: ${{ secrets.SOLSCAN_API_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        pytest tests/ --verbose  # Menjalankan pengujian dengan pytest
