name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    # Verifikasi instalasi flake8 dan pytest
    - name: Verify flake8 and pytest installation
      run: |
        pip show flake8
        pip show pytest

    # Cek struktur direktori untuk memastikan ada src/ dan tests/
    - name: Check directories structure
      run: |
        ls -R  # Menampilkan seluruh struktur direktori

    - name: Lint with flake8
      run: |
        echo "Checking flake8 version..."
        flake8 --version  # Cek versi flake8 yang terinstal
        flake8 src/ tests/ --max-line-length=120 --exclude=src/static

    - name: Run tests
      env:
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        SOLSCAN_API_KEY: ${{ secrets.SOLSCAN_API_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        pytest tests/ --verbose
