name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Verify flake8 installation
      run: |
        pip show flake8
        flake8 --version  # Memastikan flake8 terinstal

    - name: Check directory structure
      run: |
        ls -R src/  # Memastikan src/ ada
        ls -R tests/  # Memastikan tests/ ada

    - name: Lint with flake8
      run: |
        echo "Running flake8 with debug..."
        flake8 --max-line-length=120 --exclude=src/static --verbose src/ tests/

    - name: Run tests
      env:
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        SOLSCAN_API_KEY: ${{ secrets.SOLSCAN_API_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        pytest tests/ --verbose
